# Generated by Django 5.0.6 on 2024-07-13 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendoapp', '0002_inmueble_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arriendoapp.region'),
        ),
    ]
