# Generated by Django 5.0.6 on 2024-07-19 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendoapp', '0005_remove_usuario_correo_alter_usuario_apellidos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudarriendo',
            name='estado',
        ),
        migrations.AddField(
            model_name='solicitudarriendo',
            name='mensaje',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='solicitudarriendo',
            name='arrendatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudarriendo',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='arriendoapp.inmueble'),
        ),
    ]
